const mix = require('laravel-mix');
const mixObj = mix
    // Existing User Authentication
    .styles(
        [
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/new-layout.css",
            "resources/css/common/new-form.css",
            "resources/css/common/new-common.css",
            "resources/css/common/existing-user-authentication.css",
        ],
        "public/css/existing-user-authentication.css"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/new-layout.js",
            "resources/js/common/existing-user-authentication.js",
        ],
        "public/js/existing-user-authentication.js"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/new-layout.js",
            "resources/js/common/existing-user-otp-verify.js",
        ],
        "public/js/existing-user-otp-verify.js"
    )
    // Unsubscribe page
    .styles(
        [
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/jquery-ui.min.css",
            "resources/css/common/new-layout.css",
            "resources/css/common/new-form.css",
            "resources/css/common/new-common.css",
            "resources/css/common/toastr.css",
            "resources/css/common/unsubscribe.css",
        ],
        "public/css/wishfin-unsubscribe.css"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery-ui-v1.13.0.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/new-layout.js",
            "resources/js/common/toastr.min.js",
            "resources/js/common/unsubscribe.js",
        ],
        "public/js/wishfin-unsubscribe.js"
    )
    .styles(
        [
            "resources/css/common/font-Roboto.min.css",
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/jquery-ui.min.css",
            "resources/css/common/owl.carousel.min.css",
            "resources/css/common/owl.theme.default.min.css",
            "resources/css/common/form.css",
            "resources/css/common/footer.css",
            "resources/css/campaign/whatsapp/whatsapp-cibil.css",
        ],
        "public/css/campaign-whatsapp-cibil.css"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery-ui-v1.13.0.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/autoNumeric.js",
            "resources/js/common/form.js",
            "resources/js/common/owl.carousel.min.js",
            "resources/js/common/campaign-layout.js",
            'resources/js/campaign/support.js',
            "resources/js/campaign/whatsapp/whatsapp-cibil.js"
        ],
        "public/js/campaign-whatsapp-cibil.js"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery-ui-v1.13.0.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/autoNumeric.js",
            "resources/js/common/form.js",
            "resources/js/common/owl.carousel.min.js",
            "resources/js/common/campaign-layout.js",
            "resources/js/campaign/whatsapp/whatsapp.js",
            'resources/js/campaign/support.js'
        ],
        "public/js/campaign-whatsapp.js"
    )
    .styles(
        [
            "resources/css/common/font-Roboto.min.css",
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/jquery-ui.min.css",
            "resources/css/common/owl.carousel.min.css",
            "resources/css/common/owl.theme.default.min.css",
            "resources/css/common/form.css",
            "resources/css/common/footer.css",
            "resources/css/campaign/whatsapp/whatsapp.css",
        ],
        "public/css/campaign-whatsapp.css"
    )
    .styles(
        [
            "resources/css/common/font-Poppins.min.css",
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/jquery-ui.min.css",
            "resources/css/common/rangeslider.min.css",
            "resources/css/common/form.css",
            "resources/css/common/footer.css",
            "resources/css/campaign/hdfc/hdfc-personal-loan.css",
        ],
        "public/css/campaign-hdfc-personal-loan.css"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery-ui-v1.13.0.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/autoNumeric.js",
            "resources/js/common/rangeslider.js",
            "resources/js/common/form.js",
            "resources/js/common/wf_ui_autocomplete.js",
            'resources/js/campaign/support.js',
            "resources/js/campaign/hdfc/hdfc-personal-loan.js",
        ],
        "public/js/campaign-hdfc-personal-loan.js"
    )
    // Campaign HDFC PL Continue
    .styles(
        [
            "resources/css/common/font-Poppins.min.css",
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/jquery-ui.min.css",
            "resources/css/common/form.css",
            "resources/css/common/footer.css",
            "resources/css/campaign/hdfc/hdfc-personal-loan-continue.css",
        ],
        "public/css/campaign-hdfc-personal-loan-continue.css"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            "resources/js/common/jquery-ui-v1.13.0.js",
            "resources/js/common/jquery.validate.min.js",
            "resources/js/common/autoNumeric.js",
            "resources/js/common/form.js",
            'resources/js/campaign/support.js',
            "resources/js/common/wf_ui_autocomplete.js",
            "resources/js/campaign/hdfc/hdfc-personal-loan-continue.js",
        ],
        "public/js/campaign-hdfc-personal-loan-continue.js"
    )
    // Campaign HDFC PL Thanks
    .styles(
        [
            "resources/css/common/font-Poppins.min.css",
            "resources/css/common/bootstrap-v5.0.2.min.css",
            "resources/css/common/footer.css",
            "resources/css/campaign/hdfc/hdfc-personal-loan-thanks.css",
        ],
        "public/css/campaign-hdfc-personal-loan-thanks.css"
    )
    .combine(
        [
            "resources/js/common/jquery-3.6.0.js",
            "resources/js/common/popper-v2.9.2.min.js",
            "resources/js/common/bootstrap-v5.0.2.min.js",
            'resources/js/campaign/support.js',
            "resources/js/campaign/hdfc/hdfc-personal-loan-thanks.js",
        ],
        "public/js/campaign-hdfc-personal-loan-thanks.js"
    )
    .version();